version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - sbt-{{ checksum "project/build.properties" }}
            - sbt-

      - restore_cache:
          keys:
            - dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}
            - dependencies-

      - run: sbt -batch test:compile

      - save_cache:
          paths:
            - ~/.sbt
          key: sbt-{{ checksum "project/build.properties" }}

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.cache/coursier
          key: dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}

      - run: sbt -batch test

      - store_test_results:
          path: kamon1Repro/target/test-reports
      - store_test_results:
          path: kamon2Repro/target/test-reports
